#!/usr/bin/env python3
"""
PDF Report Generation Demo

This script demonstrates the capabilities of the PDF Report Generation System
in Deep Deep Research v2, including different templates, report types, and
content formatting.
"""

import os
import sys
import json
import tempfile
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime

# Add the src directory to the path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.pdf_generation import (
    PDFReport, ReportConfig, ReportLibrary, ReportElement,
    TextElement, TableElement, ChartElement, ImageElement,
    HeaderElement, FooterElement, ListElement, PageBreakElement,
    StyleSheet, ColorScheme, TextStyle, TextAlignment,
    ReportService, create_simple_report
)


def demo_simple_report():
    """Demonstrate creating a simple PDF report."""
    print("\n=== Simple PDF Report Demo ===")
    
    # Create a temporary file for output
    with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp:
        output_path = tmp.name
    
    # Create a simple report
    title = "Deep Deep Research v2 - Simple Report Demo"
    content = """
    This is a simple report generated by the Deep Deep Research v2 PDF Generation System.
    
    The system supports various formatting options including:
    • Bold and italic text
    • Multiple font families and sizes
    • Custom color schemes
    • Headers and footers
    • Page numbering
    • Tables, charts, and images
    
    This example demonstrates a basic report with just text content.
    """
    
    pdf_path = create_simple_report(
        title=title,
        content=content,
        output_path=output_path
    )
    
    print(f"Simple report generated at: {pdf_path}")
    return pdf_path


def demo_research_report():
    """Demonstrate creating a research report with different sections."""
    print("\n=== Research Report Demo ===")
    
    # Create a temporary file for output
    with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp:
        output_path = tmp.name
    
    # Create a report configuration
    config = ReportConfig(
        title="The Impact of Artificial Intelligence on Society",
        author="Deep Deep Research v2",
        subject="AI Research Report",
        keywords=["AI", "society", "ethics", "future"],
        include_toc=True,
        include_page_numbers=True
    )
    
    # Create a report
    report = PDFReport(config)
    
    # Add header and footer
    report.add_element(HeaderElement(
        text=config.title,
        height=40,
        include_date=True,
        include_page_number=True
    ))
    
    report.add_element(FooterElement(
        text=f"Generated by {config.author}",
        height=30,
        include_page_number=True
    ))
    
    # Add title
    report.add_element(TextElement(
        text=config.title,
        x=72, y=100,
        style_name="title"
    ))
    
    report.add_element(TextElement(
        text=f"Generated on: {datetime.now().strftime('%Y-%m-%d')}",
        x=72, y=130,
        style_name="heading2"
    ))
    
    report.add_element(TextElement(
        text="By: Deep Deep Research v2",
        x=72, y=150,
        style_name="heading2"
    ))
    
    # Add page break
    report.add_element(PageBreakElement())
    
    # Add executive summary
    report.add_element(TextElement(
        text="Executive Summary",
        x=72, y=72,
        style_name="heading1"
    ))
    
    report.add_element(TextElement(
        text="""
        Artificial Intelligence (AI) is rapidly transforming various aspects of society,
        including employment, healthcare, education, and personal privacy. This report
        explores the current and potential future impacts of AI on society, focusing on
        both benefits and challenges.
        
        Key findings include the potential for significant job displacement alongside the
        creation of new roles, improvements in healthcare diagnostics and treatment,
        personalized education opportunities, and concerns regarding privacy, bias, and
        the digital divide.
        """,
        x=72, y=100,
        width=450,
        style_name="body"
    ))
    
    # Add page break
    report.add_element(PageBreakElement())
    
    # Add findings section
    report.add_element(TextElement(
        text="Key Findings",
        x=72, y=72,
        style_name="heading1"
    ))
    
    # Add employment subsection
    report.add_element(TextElement(
        text="Employment Impact",
        x=72, y=100,
        style_name="heading2"
    ))
    
    report.add_element(TextElement(
        text="""
        AI technologies are expected to automate many routine tasks across industries.
        While this may lead to job displacement in some sectors, it is also expected to
        create new job categories and increase demand for workers with AI-related skills.
        """,
        x=72, y=130,
        width=450,
        style_name="body"
    ))
    
    # Add a chart showing job impact
    x = np.arange(5)
    jobs_lost = [12, 18, 25, 30, 35]
    jobs_created = [10, 15, 22, 28, 40]
    
    plt.figure(figsize=(8, 4))
    plt.bar(x - 0.2, jobs_lost, width=0.4, label='Jobs Displaced')
    plt.bar(x + 0.2, jobs_created, width=0.4, label='Jobs Created')
    plt.xlabel('Years from Present')
    plt.ylabel('Millions of Jobs')
    plt.title('Projected AI Impact on Global Employment')
    plt.xticks(x, ['1', '2', '5', '10', '15'])
    plt.legend()
    plt.tight_layout()
    
    # Save the chart to a temporary file
    with tempfile.NamedTemporaryFile(suffix='.png', delete=False) as tmp:
        chart_path = tmp.name
    plt.savefig(chart_path)
    plt.close()
    
    # Add the chart to the report
    report.add_element(ImageElement(
        image_path=chart_path,
        x=72, y=220,
        width=450
    ))
    
    # Add a table with AI skill demand
    report.add_element(TextElement(
        text="Projected Demand for AI Skills (% growth)",
        x=72, y=480,
        style_name="heading3"
    ))
    
    table_data = [
        ["Skill", "2023", "2024", "2025", "2026"],
        ["Machine Learning", "35%", "42%", "48%", "55%"],
        ["Data Science", "40%", "45%", "50%", "58%"],
        ["AI Ethics", "25%", "35%", "45%", "60%"],
        ["NLP/Computer Vision", "30%", "38%", "45%", "52%"]
    ]
    
    report.add_element(TableElement(
        data=table_data,
        x=72, y=510,
        col_widths=[150, 75, 75, 75, 75]
    ))
    
    # Add page break
    report.add_element(PageBreakElement())
    
    # Add healthcare section
    report.add_element(TextElement(
        text="Healthcare Impact",
        x=72, y=72,
        style_name="heading2"
    ))
    
    report.add_element(TextElement(
        text="""
        AI is transforming healthcare through improved diagnostics, personalized
        treatment plans, drug discovery acceleration, and operational efficiencies.
        Technologies like machine learning can analyze medical images with accuracy
        comparable to or exceeding that of human experts in some cases.
        """,
        x=72, y=100,
        width=450,
        style_name="body"
    ))
    
    # Add a list of healthcare applications
    applications = [
        "Medical imaging analysis and diagnosis assistance",
        "Predictive analytics for patient risk assessment",
        "Virtual nursing assistants and patient monitoring",
        "Drug discovery and development acceleration",
        "Hospital workflow optimization and resource allocation"
    ]
    
    report.add_element(ListElement(
        items=applications,
        x=72, y=170,
        style_name="body"
    ))
    
    # Add page break
    report.add_element(PageBreakElement())
    
    # Add conclusion
    report.add_element(TextElement(
        text="Conclusion and Recommendations",
        x=72, y=72,
        style_name="heading1"
    ))
    
    report.add_element(TextElement(
        text="""
        The integration of AI into society presents both significant opportunities and
        challenges. To maximize benefits while mitigating risks, a coordinated approach
        involving governments, industry, academia, and civil society is necessary.
        
        Key recommendations include:
        """,
        x=72, y=100,
        width=450,
        style_name="body"
    ))
    
    recommendations = [
        "Develop comprehensive AI policies and regulations",
        "Invest in AI education and workforce development",
        "Establish ethical frameworks for AI development and deployment",
        "Ensure inclusive access to AI technologies",
        "Support interdisciplinary research on AI societal impacts"
    ]
    
    report.add_element(ListElement(
        items=recommendations,
        x=72, y=170,
        style_name="body"
    ))
    
    # Add page break
    report.add_element(PageBreakElement())
    
    # Add references
    report.add_element(TextElement(
        text="References",
        x=72, y=72,
        style_name="heading1"
    ))
    
    references = [
        "Smith, J. et al. (2023). The Future of Work: AI Impact on Employment. Journal of AI Studies, 45(2), 112-128.",
        "Johnson, A. & Lee, B. (2022). AI in Healthcare: Transforming Patient Outcomes. Medical Technology Review, 18(4), 230-245.",
        "World Economic Forum. (2023). AI and the Future of Jobs Report 2023-2028.",
        "Garcia, M. et al. (2022). Ethical Considerations in AI Development. AI Ethics Journal, 5(3), 78-92.",
        "Brown, T. & Wilson, S. (2023). Education in the Age of AI. Educational Technology Review, 29(1), 45-60."
    ]
    
    report.add_element(ListElement(
        items=references,
        x=72, y=100,
        style_name="body"
    ))
    
    # Generate the PDF
    pdf_path = report.generate(output_path)
    
    # Clean up temporary files
    os.unlink(chart_path)
    
    print(f"Research report generated at: {pdf_path}")
    return pdf_path


def demo_report_service():
    """Demonstrate using the ReportService for different template styles."""
    print("\n=== Report Service Template Demo ===")
    
    # Create a dictionary with sample research results
    research_results = {
        "query": "Impact of renewable energy on climate change",
        "summary": """
        Renewable energy technologies play a crucial role in mitigating climate change
        by reducing greenhouse gas emissions. This report examines the current state
        of renewable energy adoption and its impact on global climate goals.
        """,
        "findings": [
            {
                "title": "Current Renewable Energy Adoption",
                "content": """
                Global renewable energy capacity has grown significantly over the past decade.
                Solar and wind power have seen the most substantial growth, with costs decreasing
                by over 70% for solar PV and 25% for wind power since 2010.
                """
            },
            {
                "title": "Emissions Reduction Potential",
                "content": """
                A transition to 100% renewable energy could reduce global energy-related CO2
                emissions by up to 70%. The electricity sector has shown the most progress, with
                some countries achieving over 50% renewable electricity generation.
                """
            },
            {
                "title": "Economic and Social Benefits",
                "content": """
                The renewable energy sector employs over 11 million people globally and could
                create millions more jobs by 2030. Renewable energy deployment also improves
                air quality, reducing healthcare costs and improving public health outcomes.
                """
            }
        ],
        "sources": [
            {
                "title": "IRENA Renewable Capacity Statistics 2023",
                "source_name": "International Renewable Energy Agency",
                "url": "https://www.irena.org/publications/2023/Mar/Renewable-Capacity-Statistics-2023",
                "source_type": "report"
            },
            {
                "title": "IPCC Special Report on Renewable Energy Sources and Climate Change Mitigation",
                "source_name": "Intergovernmental Panel on Climate Change",
                "url": "https://www.ipcc.ch/report/renewable-energy-sources-and-climate-change-mitigation/",
                "source_type": "report"
            },
            {
                "title": "Renewables 2022 Global Status Report",
                "source_name": "REN21",
                "url": "https://www.ren21.net/reports/global-status-report/",
                "source_type": "report"
            }
        ],
        "conclusion": """
        Accelerating the transition to renewable energy is essential for meeting climate goals.
        Policy support, technology innovation, and increased investment are key to overcoming
        barriers to widespread adoption. The economic, environmental, and social benefits of
        renewable energy make it a crucial component of sustainable development.
        """
    }
    
    # Demonstrate different template styles
    templates = ["modern", "academic", "business"]
    pdf_paths = []
    
    for template in templates:
        print(f"\nGenerating report with {template} template...")
        
        # Create a temporary file for output
        with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp:
            output_path = tmp.name
        
        # Create report service with the template
        report_service = ReportService(template_name=template)
        
        # Generate the report
        pdf_path = report_service.generate_report_from_research_results(
            research_results=research_results,
            output_path=output_path,
            title=f"Renewable Energy and Climate Change: {template.capitalize()} Template"
        )
        
        pdf_paths.append(pdf_path)
        print(f"{template.capitalize()} template report generated at: {pdf_path}")
    
    return pdf_paths


def main():
    """Run all PDF report demos."""
    print("=== PDF Report Generation System Demo ===")
    
    try:
        # Run the demos
        simple_report_path = demo_simple_report()
        research_report_path = demo_research_report()
        template_report_paths = demo_report_service()
        
        # Print summary
        print("\n=== Demo Summary ===")
        print(f"Simple report: {simple_report_path}")
        print(f"Research report: {research_report_path}")
        for i, path in enumerate(template_report_paths):
            print(f"Template report ({['modern', 'academic', 'business'][i]}): {path}")
        
        print("\nAll reports generated successfully!")
        print("You can open these PDF files to view the results.")
        
    except Exception as e:
        print(f"Error during demo: {e}")
        raise


if __name__ == "__main__":
    main() 